### ISSUE TITLE
Missing documentation for ADXL345

### ISSUE THREAD

**Issue by cad3na** [Lzhikai/SIBOOR-Voron-0.2#15]
Maybe I'm missing something, but I can't find any resource to what steps are needed to run input shaper calibration with the provided ADXL345 sensor.

**Comment by Lzhikai** [comment]
You can refer to the accelerometer tutorial made by mellow.  
https://mellow.klipper.cn/#/advanced/Accelerometer

**Comment by cad3na** [comment]
Thank you very much for the quick response! I will give this a try.

**Comment by d4rxt4r** [comment]
[mellow.klipper.cn#/advanced/Accelerometer](https://mellow.klipper.cn/#/advanced/Accelerometer)
link does not work anymore... how do i setup adxl with fly-gemnini v3?
