### ISSUE TITLE
Display update

### ISSUE THREAD

**Issue by pr0phe** [Lzhikai/SIBOOR-Voron-0.2#16]
Ive recieved the following once im trying to enable yr display.
How to update it?

MCU Protocol error

This is frequently caused by running an older version of the
firmware on the MCU(s). Fix by recompiling and flashing the
firmware.

Your Klipper version is: v0.11.0-275-g8ef0f7d7
MCU(s) which should be updated:
display: Current version v0.10.0-391-g722ad4a1-dirty-20230510_022857-flygemini
Up-to-date MCU(s):
mcu: Current version v0.11.0-275-g8ef0f7d7

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.

mcu 'display': Unable to encode: config_i2c

**Comment by Lzhikai** [comment]
You need to update the display version, refer to the official documentation     https://github.com/VoronDesign/Voron-Hardware/blob/master/V0_Display/Documentation/Setup_and_Flashing_Guide.md

**Comment by stlfatboy** [comment]
> You need to update the display version, refer to the official documentation https://github.com/VoronDesign/Voron-
Hardware/blob/master/V0_Display/Documentation/Setup_and_Flashing_Guide.md

Follows flash guide, but ls /dev/serial/by-id/* not showing the device.

Found it boot into DFU mode again.

Using 0.12 klipper

=================================
sudo dfu-util -d ,0483:df11 -R -a 0 -s 0x8000000:leave -D out/klipper.bin

dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

dfu-util: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
Opening DFU capable USB device...
ID 0483:df11
Run-time device DFU version 011a
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: state = dfuERROR, status = 10
dfuERROR, clearing status
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 011a
Device returned transfer size 2048
DfuSe interface name: "Internal Flash "
Downloading to address = 0x08000000, size = 21156
Download [=========================] 100% 21156 bytes
Download done.
File downloaded successfully
dfu-util: Error during download get_status

Failed to flash to 0483:df11: Error running dfu-util

If the device is already in bootloader mode it can be flashed with the
following command:
make flash FLASH_DEVICE=0483:df11
OR
make flash FLASH_DEVICE=1209:beba

If attempting to flash via 3.3V serial, then use:
make serialflash FLASH_DEVICE=0483:df11

make: *** [src/stm32/Makefile:111: flash] Error 255

...
lsusb
Bus 008 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 007 Device 049: ID 0483:df11 STMicroelectronics STM Device in DFU Mode
...

**Comment by Lzhikai** [comment]
"Download [==========================] 100% 21156 bytes" When this command appears, the programming has been completed. Is the boot pin connected? The jumper cap needs to be removed

> > You need to update the display version, refer to the official documentation https://github.com/VoronDesign/Voron-
> > Hardware/blob/master/V0_Display/Documentation/Setup_and_Flashing_Guide.md
> 
> Follows flash guide, but ls /dev/serial/by-id/* not showing the device.
> 
> Found it boot into DFU mode again.
> 
> Using 0.12 klipper
> 
> ================================= sudo dfu-util -d ,0483:df11 -R -a 0 -s 0x8000000:leave -D out/klipper.bin
> 
> dfu-util 0.9
> 
> Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc. Copyright 2010-2016 Tormod Volden and Stefan Schmidt This program is Free Software and has ABSOLUTELY NO WARRANTY Please report bugs to http://sourceforge.net/p/dfu-util/tickets/
> 
> dfu-util: Invalid DFU suffix signature dfu-util: A valid DFU suffix will be required in a future dfu-util release!!! Opening DFU capable USB device... ID 0483:df11 Run-time device DFU version 011a Claiming USB DFU Interface... Setting Alternate Setting #0 ... Determining device status: state = dfuERROR, status = 10 dfuERROR, clearing status Determining device status: state = dfuIDLE, status = 0 dfuIDLE, continuing DFU mode device DFU version 011a Device returned transfer size 2048 DfuSe interface name: "Internal Flash " Downloading to address = 0x08000000, size = 21156 Download [=========================] 100% 21156 bytes Download done. File downloaded successfully dfu-util: Error during download get_status
> 
> Failed to flash to 0483:df11: Error running dfu-util
> 
> If the device is already in bootloader mode it can be flashed with the following command: make flash FLASH_DEVICE=0483:df11 OR make flash FLASH_DEVICE=1209:beba
> 
> If attempting to flash via 3.3V serial, then use: make serialflash FLASH_DEVICE=0483:df11
> 
> make: *** [src/stm32/Makefile:111: flash] Error 255
> 
> ... lsusb Bus 008 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub Bus 007 Device 049: ID 0483:df11 STMicroelectronics STM Device in DFU Mode ...

"Download [==========================] 100% 21156 bytes" When this command appears, the programming has been completed. Is the boot pin connected? The jumper cap needs to be removed

**Comment by stlfatboy** [comment]
jumper pin keep removed before flashing

**Comment by stlfatboy** [comment]
It seems to be a hardware failure.  Got a new one from seller which works.
