### ISSUE TITLE
unsafe default settings

### ISSUE THREAD

**Issue by shiftingtech** [Lzhikai/SIBOOR-Voron-0.2#18]
It is dramatically dangerous to set min_temp:-100 on the extruder and bed, as seen in your printer.cfg

This setting effectively disables the first line of defense against wire breaks or thermistor failures

**Comment by Lzhikai** [comment]
This is the lowest temperature, not the highest temperature, so the danger is not as high as you think. You can make a modification, and I will update later

**Comment by shiftingtech** [comment]
This is not correct information:  a wire break causes a negative reading.

**Comment by Lzhikai** [comment]
I'm modifying it now, thanks for the heads up

**Comment by Lzhikai** [comment]
Changed it to -10, so I'm about to close the place.
